# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

QuickReg <- function(X, Y) {
    .Call('_BDFM_QuickReg', PACKAGE = 'BDFM', X, Y)
}

comp_form <- function(B) {
    .Call('_BDFM_comp_form', PACKAGE = 'BDFM', B)
}

mvrnrm <- function(n, mu, Sigma) {
    .Call('_BDFM_mvrnrm', PACKAGE = 'BDFM', n, mu, Sigma)
}

rinvwish <- function(n, v, S) {
    .Call('_BDFM_rinvwish', PACKAGE = 'BDFM', n, v, S)
}

invchisq <- function(nu, scale) {
    .Call('_BDFM_invchisq', PACKAGE = 'BDFM', nu, scale)
}

stack_obs <- function(nn, p, r = 0L) {
    .Call('_BDFM_stack_obs', PACKAGE = 'BDFM', nn, p, r)
}

PrinComp <- function(Y, m) {
    .Call('_BDFM_PrinComp', PACKAGE = 'BDFM', Y, m)
}

BReg <- function(X, Y, Int, Bp, lam, nu, reps = 1000L, burn = 1000L) {
    .Call('_BDFM_BReg', PACKAGE = 'BDFM', X, Y, Int, Bp, lam, nu, reps, burn)
}

BReg_diag <- function(X, Y, Int, Bp, lam, nu, reps = 1000L, burn = 1000L) {
    .Call('_BDFM_BReg_diag', PACKAGE = 'BDFM', X, Y, Int, Bp, lam, nu, reps, burn)
}

DSmooth <- function(B, q, H, R, Y) {
    .Call('_BDFM_DSmooth', PACKAGE = 'BDFM', B, q, H, R, Y)
}

DSUF <- function(B, q, H, R, Y) {
    .Call('_BDFM_DSUF', PACKAGE = 'BDFM', B, q, H, R, Y)
}

FSimUF <- function(B, q, H, R, Y) {
    .Call('_BDFM_FSimUF', PACKAGE = 'BDFM', B, q, H, R, Y)
}

EstDFM <- function(B, Bp, lam_B, q, nu_q, H, Hp, lam_H, R, nu_r, Y, reps = 1000L, burn = 500L, Loud = FALSE) {
    .Call('_BDFM_EstDFM', PACKAGE = 'BDFM', B, Bp, lam_B, q, nu_q, H, Hp, lam_H, R, nu_r, Y, reps, burn, Loud)
}

Ksmoother <- function(A, Q, HJ, R, Y) {
    .Call('_BDFM_Ksmoother', PACKAGE = 'BDFM', A, Q, HJ, R, Y)
}

KestExact <- function(A, Q, H, R, Y, itc, m, p) {
    .Call('_BDFM_KestExact', PACKAGE = 'BDFM', A, Q, H, R, Y, itc, m, p)
}

KSeas <- function(B, q, M, r, Y, N) {
    .Call('_BDFM_KSeas', PACKAGE = 'BDFM', B, q, M, r, Y, N)
}

